### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by verbumfeit** [KaOS-Community-Packages/gimp-plugin-registry#2]
As far as I can see the gimp-plugin-registry is not maintained anymore (https://www.gimpusers.com/forums/gimp-user/21164-gimp-2-10-8-plugin-registry)

Maybe it's time to remove it?

**Comment by ShalokShalom** [comment]
Also not working on the current version of GIMP; which is the only available one in KaOS. The version in this repo here is 6 years old. Thanks for pointing it out.

**Comment by demmm** [comment]
Since no-one else is responding, I'll remove it, was hoping some active in KCP would offer to delete....
